version: '2' # specify docker-compose version

# Define the services/containers to be run
services:
  angular: # name of the first service
    restart: always
    build: client # specify the directory of the Dockerfile
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "4200:4200" # specify port forewarding
      - "49153:49153"
    links: 
      - api # link this service to the api service

  api: #name of the second service
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules
    build: api # specify the directory of the Dockerfile
    ports:
      - "3000:3000" #specify ports forewarding
    links:
      - database # link this service to the database service

  database: # name of the third service
    image: mongo # specify image to build container from
    ports:
      - "27017:27017" # specify port forewarding
  